language: go
sudo: false
go:
  - 1.7
  - master
before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/sirupsen/logrus
  - go get github.com/libp2p/go-libp2p/p2p
  - go get github.com/multiformats/go-multiaddr
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
